/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package StudentManagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author nadafr
 */
public class AddMarks extends javax.swing.JFrame {

    /**
     * Creates new form AddMarks
     */
    public AddMarks() {
        initComponents();
    }
    
     Connection con;
    PreparedStatement pst;
    
    
    
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField6 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSubmit = new javax.swing.JButton();
        txtCancel = new javax.swing.JButton();
        txtEnglish = new javax.swing.JTextField();
        txtHindi = new javax.swing.JTextField();
        txtSocial = new javax.swing.JTextField();
        txtMathematics = new javax.swing.JTextField();
        txtScience = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtRoll = new javax.swing.JTextField();

        jTextField6.setText("jTextField6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("English");

        jLabel3.setText("Hindi");

        jLabel4.setText("Social Studeis");

        jLabel5.setText("Mathematics");

        jLabel6.setText("Science");

        txtSubmit.setText("Submit");
        txtSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubmitActionPerformed(evt);
            }
        });

        txtCancel.setText("Cancel");
        txtCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCancelActionPerformed(evt);
            }
        });

        jLabel7.setText("Roll No");

        txtRoll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRollActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(txtSubmit)
                        .addGap(31, 31, 31)
                        .addComponent(txtCancel))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(46, 46, 46)))
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMathematics)
                            .addComponent(txtSocial, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtHindi, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtEnglish, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtRoll, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtScience))))
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtRoll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEnglish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtHindi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMathematics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtScience, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSubmit)
                    .addComponent(txtCancel))
                .addGap(82, 82, 82))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubmitActionPerformed
        // TODO add your handling code here:
        
        if(txtRoll.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this,"Please enter Roll Number");
        }
        else if(txtEnglish.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this,"Please enter English marks");
        }
        else if(txtHindi.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this,"Please enter Hindi marks");
        }
        else if(txtSocial.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this,"Please enter Social marks");
        }
        else  if(txtMathematics.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this,"Please enter Matehmatics marks");
        }
         else  if(txtScience.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this,"Please enter Science marks");
        }
           else
         {
            try {
                
                String rollno=txtRoll.getText();
                float english=Float.parseFloat(txtEnglish.getText());
                float hindi=Float.parseFloat(txtHindi.getText());
                float mathematics=Float.parseFloat(txtMathematics.getText());
                float social=Float.parseFloat(txtSocial.getText());
                float science=Float.parseFloat(txtScience.getText());
                float avg;
              
               String grade=null;
                
                avg=(english+hindi+social+mathematics+science);
                Float average=avg/5;
                 
                
                if(average<60){
                    grade="F";
                }
                else if(average<70){
                    grade="D";
                }
                else if(average<80){
                    grade="C";
                }
                else if(average<90){
                    grade="B";
                }
                else if(average<=100){
                    grade="A";
                            
                }
                
                Class.forName("com.mysql.jdbc.Driver");
                con=DriverManager.getConnection("jdbc:mysql://localhost/studentmanagement","root","");
              
                pst=con.prepareStatement("insert into marks(rollno,english,hindi,social,mathematics,science,average,grade)values(?,?,?,?,?,?,?,?)");
                pst.setString(1, rollno);
                pst.setFloat(2, english);
                pst.setFloat(3, hindi);
                pst.setFloat(4, social);
                pst.setFloat(5, mathematics);
                pst.setFloat(6, science);
                pst.setFloat(7, average);
                pst.setString(8, grade);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null,"Marks added successfully....");
                txtRoll.setText("");
                txtEnglish.setText("");
                txtHindi.setText("");
                txtSocial.setText("");
                txtMathematics.setText("");
                txtScience.setText("");
                txtRoll.requestFocus();
                
                 Main m=new Main();
            this.hide();
            m.setVisible(true);
                
                con.close();
               
                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AddMarks.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                 Logger.getLogger(AddMarks.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null,"Duplicate roll no or roll no doesnot exist...");
               
            }
               
             
             
             
             
             
         }
    }//GEN-LAST:event_txtSubmitActionPerformed

    private void txtCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCancelActionPerformed
        // TODO add your handling code here:
                txtRoll.setText("");
                txtEnglish.setText("");
                txtHindi.setText("");
                txtSocial.setText("");
                txtMathematics.setText("");
                txtScience.setText("");
                txtRoll.requestFocus();
                
                 Main m=new Main();
            this.hide();
            m.setVisible(true);
    }//GEN-LAST:event_txtCancelActionPerformed

    private void txtRollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRollActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRollActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddMarks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JButton txtCancel;
    public static javax.swing.JTextField txtEnglish;
    public static javax.swing.JTextField txtHindi;
    public static javax.swing.JTextField txtMathematics;
    private javax.swing.JTextField txtRoll;
    public static javax.swing.JTextField txtScience;
    public static javax.swing.JTextField txtSocial;
    private javax.swing.JButton txtSubmit;
    // End of variables declaration//GEN-END:variables
}
