/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package StudentManagement;

import static StudentManagement.StudentDetails.table1;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message.RecipientType;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;

/**
 *
 * @author nadafr
 */
public class mail extends javax.swing.JFrame {

    /**
     * Creates new form mail
     */
    public mail() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtMail = new javax.swing.JTextField();
        txtSend = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Recipient's mail address");

        txtSend.setText("Send");
        txtSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(369, 369, 369)
                .addComponent(txtSend, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86)
                .addComponent(txtSend)
                .addContainerGap(245, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSendActionPerformed
        // TODO add your handling code here:
        
         Properties props=new Properties();
         props.put("mail.smtp.host","smtp.gmail.com");
         props.put("mail.smtp.port", 465);
         props.put("mail.smtp.user", "raffinadaf55@gmail.com");
         props.put("mail.smtp.auth", "true");
         props.put("mail.smtp.starttls.enable", "true");
         props.put("mail.smtp.debug", "true");
         props.put("mail.smtp.socketFactory.port", 465);
         props.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
         props.put("mail.smtp.socketFactory.fallback", "false");
         
         // String path="";
        //JFileChooser j=new JFileChooser();
        //j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        //int x=j.showSaveDialog(this);
        
       // if(x==JFileChooser.APPROVE_OPTION)
       // {
          //  path=j.getSelectedFile().getPath();
   // }                                        
    Document doc=new Document();
    
        try {
            PdfWriter.getInstance(doc, new FileOutputStream("details.pdf"));
            doc.open();
           PdfPTable tb1=new PdfPTable(9);
           tb1.addCell("Roll no");
           tb1.addCell("Name");
           tb1.addCell("Father's name");
           tb1.addCell("Mother's name");
           tb1.addCell("Gender");
           tb1.addCell("DOB");
           tb1.addCell("Phone");
           tb1.addCell("Average");
           tb1.addCell("Grade");
           
           for(int i=0;i<table1.getRowCount();i++)
           {
              String rollno=table1.getValueAt(i,0).toString();
              String name=table1.getValueAt(i,1).toString();
              String fathername=table1.getValueAt(i,2).toString();
              String mothername=table1.getValueAt(i,3).toString();
              String gender=table1.getValueAt(i,4).toString();
              String dob=table1.getValueAt(i,5).toString();
              String phone=table1.getValueAt(i,6).toString();
              String average=table1.getValueAt(i,7).toString();
              String grade=table1.getValueAt(i,8).toString();
              
              tb1.addCell(rollno);
              tb1.addCell(name);
              tb1.addCell(fathername);
              tb1.addCell(mothername);
              tb1.addCell(gender);
              tb1.addCell(dob);
              tb1.addCell(phone);
              tb1.addCell(average);
              tb1.addCell(grade);
              
              doc.add(tb1);
              
              
           }
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(StudentDetails.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(StudentDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Session session=Session.getDefaultInstance(props,null);
        session.setDebug(true);
        MimeMessage message=new MimeMessage(session);
        try {
            
            message.setFrom(new InternetAddress("raffinadaf555@gmil.com"));
             message.addRecipient(RecipientType.TO, new InternetAddress(txtMail.getText().trim()));
             message.saveChanges();
             Transport transport=session.getTransport("smtp");
             transport.connect("smtp.gmail.com","raffinadaf555@gmail.com","Raffi@555");
             transport.sendMessage(message,message.getAllRecipients());
             transport.close();
             JOptionPane.showMessageDialog(this,"Mail sent successfully");
            
        } catch (MessagingException ex) {
            Logger.getLogger(mail.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
    
    
    }//GEN-LAST:event_txtSendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtMail;
    private javax.swing.JButton txtSend;
    // End of variables declaration//GEN-END:variables
}
